### ISSUE TITLE
Discussion: Any support for "no-bundling" specific node module dependencies?

### ISSUE THREAD

**Issue by itsdouges** [ManBearTM/vite-plugin-no-bundle#10]
Hey mate, found your plugin thanks to Google. I'm currently in the process of creating a new VSCode extension. Unfortunately the CLI that would "collect all node module" dependencies for you, to output to a build folder, [doesn't work with pnpm](https://github.com/microsoft/vscode-vsce/issues/421). 

The advised work around is: bundle your whole extension instead. Unfortunately for me some of my dependencies don't work when bundled e.g. one has fs calls that assume the file isn't bundled.

So I'm looking for a solution where I can "no bundle" some dependencies from node modules. Would need to be a finite list I can pass in as config, and it would also have to be recursive (so, bring in all of their dependencies as well).

From playing with your plugin locally it doesn't look like it supports this use case?

- must "no bundle" / copy node module dependencies to dist folder (that are listed via config) — unsure if this works as it's currently only needed for workspace dependencies
- must "no bundle" / copy local work space dependencies to dist folder (that are listed via config) — this seems to work
- must be recursive for dependencies of dependencies in node modules / workspace modules — doesn't seem to work? needs to support specifying what dependencies could be bundled but assume none by default
-  must allow the entrypoint app to be bundled where appropriate — currently looks like it's unbundled.

Keen to know your thoughts, thanks mate.

**Comment by ManBearTM** [comment]
I'm not sure I fully understand your use case, but I will try to answer to the best of my ability 😄 

The plugin, in its default configuration, basically just copies your entire dependency tree (starting from the entry point specified in vite.config.ts) to the dist folder, while applying other plugins/transformations (such as TS->JS). This means the output in `dist` still needs to be consumed by a "bundler" or something that knows how to resolve modules, since `node_modules` are not copied by default. You can however use the `internal` config to copy node modules as well. Something like this:

```ts
noBundle({ internal: 'node_modules/**' })
```

This should bring ALL node modules into the dist folder, but you can also list individual node modules instead. If you want to only bring over certain node modules AND their sub dependencies, then I don't think this is something this plugin can (or should) handle. But perhaps you could solve that by using some sort of "dependency analyzer" tool and then build the `internal` config array from that?

For the "must allow the entrypoint app to be bundled where appropriate — currently looks like it's unbundled." - I don't know how to support this hybrid approach, might not be possible without a major rewrite.

I might be of more help if you could provide me with an example source tree, showing me the source files and how you would like it to be in the dist folder. Something like this example from the README:

```
.
├── dist/
│   ├── index.js
│   ├── card.css
│   ├── table.css
│   ├── createTable.js
│   └── fetchData.js
├── src/
│   ├── index.ts
│   ├── card.css
│   ├── table.css
│   ├── createTable.js
│   └── fetchData.ts
├── package.json
├── package-lock.json
├── tsconfig.json
└── vite.config.ts
```

**Comment by itsdouges** [comment]
> If you want to only bring over certain node modules AND their sub dependencies

Yeah, this is basically the use case. I need to prepare a fully baked node modules folder that can be deployed where appropriate (in this instance: to vscode extensions).

pnpm + workspaces + symlinks are causing a lot of headaches for me right now :'). Oh well. Thanks mate appreciate the response!
